<div class="page-title">
    <h1><?php echo $this->escapeHtml($this->__('My passport details')) ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->escapeUrl($this->getUrl('passportmrz/validate/post')) ?>" method="post"
      autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->escapeHtml($this->__('My passport details')) ?></h2>
        <ul class="form-list">
            <li>
                <div class="tab-pane active" id="Passport">
                    <div class="welcome-msg">
                        <p>At the bottom of your passport there are two lines with many chevrons
                            (<?php echo $this->escapeHtml($this->getFillerChar()) ?>). Each one of them have 44
                            characters in total. Enter all the characters on each line including the chevrons on the two
                            boxes provided. The first line only includes letters and chevrons, whereas the second one
                            starts with numbers and also has letters.</p>
                    </div>
                    <label for="passportmrzlp">
                        <?php echo $this->escapeHtml($this->__('Passport number line 1 (44 characters)')) ?>
                    </label>
                    <div class="input-box">
                        <input type="text" name="passport_mrzl1" id="passportmrzlp"
                               value="<?php echo $this->escapeHtml($this->getPassportMrzl1()) ?>"
                               title="<?php echo $this->escapeHtml($this->__('Passport Mrz')) ?>"
                               class="input-text validate-passport-mrz"/>
                    </div>
                    <label for="passportmrzlt">
                        <?php echo $this->escapeHtml($this->__('Passport number line 2 (44 characters)')) ?>
                    </label>
                    <div class="input-box">
                        <input type="text" name="passport_mrzl2" id="passportmrzlt"
                               value="<?php echo $this->escapeHtml($this->getPassportMrzl2()) ?>"
                               title="<?php echo $this->escapeHtml($this->__('Passport Mrz')) ?>"
                               class="input-text validate-passport-mrz"/>
                    </div>
            </li>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                <small>&laquo;</small><?php echo htmlspecialchars($this->__('Back')) ?></a></p>
        <button type="submit" title="<?php echo htmlspecialchars($this->__('Submit request')) ?>" class="button">
            <span><span><?php echo htmlspecialchars($this->__('Submit request')) ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate');
    var errMsg = 'Your passport number can only include letters, numbers and chevron (<) and must be 44 characters';
    Validation.add('validate-passport-mrz', errMsg, function (field_value) {
        if (/^$|^([a-zA-Z0-9<]{44})$/.test(field_value)) {
            return true;
        }
        return false;
    });
    //]]>
</script>